server:
  port: 8081
spring:
  application:
    name: spring-cloud-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    appname: "rest"