server:
  port: 8083
spring:
  application:
    name: scheduler
  data:
    mongodb:
      port: 27018
      database: adventures
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}
    health-check-url-path: ${management.endpoints.web.base-path}/${management.endpoints.web.path-mapping.health}

window:
  delay: 10
  size: 100

scheduler:
  delay: 300000

services:
  core:
    instance:
      name: core
  auth:
    instance:
      name: auth_server
service.user:
  username: service_user
  password: 12345


management:
  endpoints:
    web:
      base-path: /public
      path-mapping:
        health: health-check
  endpoint:
    health:
      show-details: always
