server:
  port: 8083
spring:
  application:
    name: spring-cloud-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    appname: "scheduler"
    health-check-url-path: ${management.endpoints.web.base-path}/${management.endpoints.web.path-mapping.health}

management:
  endpoints:
    web:
      base-path: /public
      path-mapping:
        health: health-check
  endpoint:
    health:
      show-details: always
